services:
  scylladb-a:
    image: scylladb/scylla:5.4
    container_name: scylladb-a
    command: >
      --smp 2 --memory 2G --overprovisioned 1
      --seeds 192.168.56.11,192.168.56.12
      --listen-address 192.168.56.11
      --broadcast-address 192.168.56.11
      --broadcast-rpc-address 192.168.56.11
      --endpoint-snitch GossipingPropertyFileSnitch
    environment:
      - SCYLLA_DC=dc-a
      - SCYLLA_RACK=rack1
    network_mode: host

  redpanda-a:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.1
    container_name: redpanda-a
    command:
      - redpanda start --smp 1 --memory 1G --overprovisioned
      - --kafka-addr internal://192.168.56.11:9092
      - --advertise-kafka-addr internal://192.168.56.11:9092
    network_mode: host

  nats-a:
    image: nats:2.10-alpine
    container_name: nats-a
    command: ["-cluster", "nats://0.0.0.0:6222",
              "-routes", "nats://192.168.56.12:6222"]
    network_mode: host
